version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysqlversion: '3'
      
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 4563
      MYSQL_DATABASE: url_shortener_db      
      MYSQL_USER: root
      MYSQL_PASSWORD: 4563
    ports:
      - "3310:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d    

phpmyadmin:
    image: phpmyadmin:latest
    ports:
    - 9001:80
    environment:
      - PMA_ARBITRARY=1